# Generated by Django 5.2.2 on 2025-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0005_alter_modelentry_category_alter_modelentry_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('nama_model', models.CharField(max_length=100)),
                ('objectives', models.TextField()),
                ('experience', models.TextField()),
                ('implementation', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Engineering',
        ),
        migrations.AddField(
            model_name='datasetrequest',
            name='nama_model',
            field=models.CharField(default='default_model', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetrequest',
            name='no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='nama_model',
            field=models.CharField(default='default_model', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalmodel',
            name='nama_model',
            field=models.CharField(default='default_model', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalmodel',
            name='no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetrequest',
            name='kebutuhan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datasetresponse',
            name='nama_dataset',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetresponse',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='dokumentasi_link',
            field=models.URLField(default='default_link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='status_project',
            field=models.CharField(max_length=50),
        ),
    ]
