# Generated by Django 5.2.2 on 2025-06-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0006_engineeringdata_delete_engineering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('On Going', 'On Going')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
