# Generated by Django 5.2.2 on 2025-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0007_modelactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
