# Generated by Django 5.2.2 on 2025-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0008_creationentry_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
