# Generated by Django 5.2.2 on 2025-06-15 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0009_modelactivity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 15, 16, 56, 41, 467507)),
            preserve_default=False,
        ),
    ]
