# Generated by Django 5.2.2 on 2025-06-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0010_modelentry_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('nama_model', models.CharField(max_length=100)),
                ('akurasi', models.CharField(max_length=20)),
                ('metrics_tambahan', models.TextField()),
                ('status_acc', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('nama_model', models.CharField(max_length=100)),
                ('status_project', models.CharField(max_length=50)),
                ('final_model', models.TextField()),
                ('dokumentasi_link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FinalModel',
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
