# Generated by Django 5.2.2 on 2025-06-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0011_projectmanagement_systemimplementation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='Anonim', max_length=100)),
                ('nama_model', models.CharField(max_length=100)),
                ('kebutuhan', models.CharField(max_length=255)),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_description', models.TextField(blank=True, null=True)),
                ('dataset_status', models.CharField(max_length=50)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status_pilihan', models.CharField(default='Sudah Dipilih', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaProjek', models.TextField()),
                ('meaningful', models.FileField(upload_to='dokumen/')),
                ('experience', models.FileField(upload_to='dokumen/')),
                ('implementasi', models.FileField(upload_to='dokumen/')),
                ('batasan', models.FileField(upload_to='dokumen/')),
                ('perencanaan', models.FileField(upload_to='dokumen/')),
            ],
        ),
        migrations.DeleteModel(
            name='DatasetResponse',
        ),
        migrations.DeleteModel(
            name='EngineeringData',
        ),
        migrations.RemoveField(
            model_name='datasetrequest',
            name='no',
        ),
        migrations.RemoveField(
            model_name='projectmanagement',
            name='metrics_tambahan',
        ),
        migrations.RemoveField(
            model_name='projectmanagement',
            name='no',
        ),
        migrations.RemoveField(
            model_name='systemimplementation',
            name='dokumentasi_link',
        ),
        migrations.RemoveField(
            model_name='systemimplementation',
            name='final_model',
        ),
        migrations.RemoveField(
            model_name='systemimplementation',
            name='no',
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='status_model',
            field=models.CharField(default='jalan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemimplementation',
            name='dokumentasi_model',
            field=models.URLField(default='jalan', help_text='Link ke Google Colab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemimplementation',
            name='laporan_model',
            field=models.FileField(blank=True, help_text='Upload PDF laporan model', null=True, upload_to='laporan/'),
        ),
        migrations.AlterField(
            model_name='modelentry',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='akurasi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='nama_model',
            field=models.CharField(default='default_model', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemimplementation',
            name='nama_model',
            field=models.CharField(default='default_model', max_length=100),
        ),
    ]
