# Generated by Django 5.2.2 on 2025-06-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0013_remove_toexperience_batasan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemFraming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('input_features', models.TextField()),
                ('planned_process', models.TextField()),
                ('expected_output', models.CharField(max_length=255)),
                ('dataset_needed', models.TextField()),
            ],
        ),
    ]
