# Generated by Django 5.2.2 on 2025-06-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0014_problemframing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanagement',
            name='akurasi',
        ),
        migrations.RemoveField(
            model_name='projectmanagement',
            name='status_acc',
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='deskripsi_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='nama_kelompok',
            field=models.CharField(default='intellegence_Creation', max_length=100),
            preserve_default=False,
        ),
    ]
