# Generated by Django 5.2.2 on 2025-07-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0015_remove_projectmanagement_akurasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimplementation',
            name='no',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
