# Generated by Django 5.2.2 on 2025-07-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0016_systemimplementation_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toexperience',
            old_name='batasan_path',
            new_name='batasan',
        ),
        migrations.RenameField(
            model_name='toexperience',
            old_name='experience_path',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='toexperience',
            old_name='implementasi_path',
            new_name='implementasi',
        ),
        migrations.RenameField(
            model_name='toexperience',
            old_name='meaningful_path',
            new_name='meaningful',
        ),
        migrations.RenameField(
            model_name='toexperience',
            old_name='perencanaan_path',
            new_name='perencanaan',
        ),
    ]
