# Generated by Django 5.2.2 on 2025-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0017_rename_batasan_path_toexperience_batasan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toexperience',
            name='batasan',
            field=models.FileField(default='none', upload_to='laporan/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toexperience',
            name='experience',
            field=models.FileField(default='none', upload_to='laporan/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toexperience',
            name='implementasi',
            field=models.FileField(default='none', upload_to='laporan/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toexperience',
            name='meaningful',
            field=models.FileField(default='none', upload_to='laporan/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toexperience',
            name='namaProjek',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='toexperience',
            name='perencanaan',
            field=models.FileField(default='none', upload_to='laporan/'),
            preserve_default=False,
        ),
    ]
